### ISSUE TITLE
crs must match between DEM and inundation polygon

### ISSUE THREAD

**Issue by jeremyEudaric** [csdms-contrib/fwdet#18]
Dear Team,
Thank you for your previous help. l currently ruining fwdet with my own  data DEM (30 m) and my flood polygon : 
![Screenshot from 2024-05-13 20-28-36](https://github.com/csdms-contrib/fwdet/assets/79277563/e5abe742-e249-4ed7-92e6-d9a4387da662)

However l got the error message  "crs must match between DEM and inundation polygon and l don not really know why" l used your version 2.
![Screenshot from 2024-05-13 20-30-21](https://github.com/csdms-contrib/fwdet/assets/79277563/93a785f9-12ed-47d2-8766-e70df9dcf726)

Does fwdet work with hydro logical DEM or only data like this ?

![Screenshot from 2024-05-13 20-40-23](https://github.com/csdms-contrib/fwdet/assets/79277563/0e2e989a-f903-423b-af3e-e4b17c382f58)

My guess its that the border of the inundation are not clear ? Its not an unique map ( but in a real scenario is often the case) Do you have an idea how could l fix it ?
Thank you for your help.

**Comment by roescob** [comment]
Are your DEM raster and vector flood extent under the same projection? If not, try the resampling tools so that they match projections.

**Comment by jeremyEudaric** [comment]
Thanks a lot
Now l get this weird error message its still not working :/ 
![Screenshot from 2024-05-13 21-06-47](https://github.com/csdms-contrib/fwdet/assets/79277563/9adf4da5-aa65-4a80-a42a-f9323d82a4c3)

**Comment by cefect** [comment]
Looks like something is wrong with your inputs. Were you able to run on the test data? Try clipping your data down to a small sample set and see if you can get that to run. If that still doesn't run please upload your data along with your log files and we can take a look.

**Comment by jeremyEudaric** [comment]
Thank you very much for your kindness and time. l run the test set and its working, l tried on a small sample and l have the same issue. Where can l send you my data the DEM and the flood polygon ?
Again thank you very much :)

**Comment by jeremyEudaric** [comment]
Just o make a test even though its not he same geolocalisation l used my flood map(polygon) and the DEM that you provided and l got the same error message : 
Unable to execute algorithm
Could not load source layer for INPUT_B: /tmp/processing_WCMLLP/53918b8ffc634bcdbbc26e04a9f96fdf/OUTPUT.tif not found
Unable to execute algorithm
Could not load source layer for INPUT_B: /tmp/processing_WCMLLP/53918b8ffc634bcdbbc26e04a9f96fdf/OUTPUT.tif not found
Execution failed after 0.29 seconds

**Comment by jeremyEudaric** [comment]
l guess the issue is the flood map. May because its not uniform ? 
![Uploading Screenshot from 2024-05-14 09-07-11.png…]()

**Comment by jeremyEudaric** [comment]
Dear Team l finally found the issue the flood map polygon need to be in a gejson format and then we need to resize the DEM on QGIS. Now l have some results but l think they are a new issue because l have a water depth between 1 and 31 m and how you can see on the image they are withe parts. What could be the issue ? 
![Screenshot from 2024-05-14 09-50-55](https://github.com/csdms-contrib/fwdet/assets/79277563/5759d98c-828a-4ee1-bb3f-758e286bd76b)
Thanks a lot for your support

**Comment by jeremyEudaric** [comment]
l think the issue is because of this 
![Screenshot from 2024-05-14 13-57-30](https://github.com/csdms-contrib/fwdet/assets/79277563/d8d58d8a-5f4d-4501-918a-9e57abeadaec)

**Comment by cefect** [comment]
Like I said, it is difficult to debug this without more information. If you can upload your log files and inputs, I can take a closer look. You can do this with any file sharing platform like Google Drive or wetransfer.

**Comment by jeremyEudaric** [comment]
Deeply thank you for your kindness

https://drive.google.com/drive/folders/18km7boOaIIRpoDeJ7S1IlfVWItbRtolq?usp=drive_link

**Comment by jeremyEudaric** [comment]
Dear Team thank you for your help, its finally working (l hope) l resized my DEM thanks to QGIS  (Warp re projected) and l used a DEM of Tiff (32-float type) from Copernicus.

![results](https://github.com/csdms-contrib/fwdet/assets/79277563/7ef5dcba-0fff-4566-854e-1d5b0c2f7f94)

However l have an issue with the results l have a water depth between 0 and 0.12 that doesn´t make sens. Could you giv em you point of view if you have time. l upload the new DEM and polygon 

Thanks a lot for your amazing support
