### ISSUE TITLE
Water Depth issue 

### ISSUE THREAD

**Issue by jeremyEudaric** [csdms-contrib/fwdet#19]
Dear Team thank you for your help and time , its finally working (l hope) l resized my DEM thanks to QGIS (Warp re projected) and l used a DEM of Tiff (32-float type) from Copernicus. However l have an issue with the results l have a water depth between 0 and 0.12 that doesn´t make sens. Could you give me you point of view if you have time. 

![results](https://github.com/csdms-contrib/fwdet/assets/79277563/48683658-5329-49c2-bad8-0710f06bfe92)

Also looks like fwdet does not take all the inundation map as you can see on this screen. Do you have an idea as well how l could fix this issue ? :)

![C](https://github.com/csdms-contrib/fwdet/assets/79277563/17f1f4f3-4392-4564-b983-ea5882b25e3c)

Thank you very much for your kindness and time

**Comment by cefect** [comment]
This can happen if there is a poor match between your DEM and the polygon. I suggest starting with a smaller area to try and understand the issue. If this doesn't work, please upload the data and I can take a look.

Regards

**Comment by jeremyEudaric** [comment]
Thank you for your reply and time unfortunate l try with a smaller area and l still have the same issue fwdet does not take all the inundation map and  l have a water depth between 0 and 0.12 that doesn´t make sens. Do you have an idea why ?

You will fin d attached the link to download the data.

https://drive.google.com/file/d/1hE4NjL_sDL8gQ-zibVEm3iGU9c1MsPXg/view?usp=drive_link

Thank you very much for your time

**Comment by jeremyEudaric** [comment]
Thanks a lot for your help, l tried to "clip the raster by mask layer"  to improve the match but its still not working well with the same CRS
![pp](https://github.com/csdms-contrib/fwdet/assets/79277563/226ca43b-9414-41fb-90b9-75d13a144ed1)

Also l have a water depth like these does it make sens ? Do l need to label my water depth myself ? For instance between 0-6 m ?

![wt](https://github.com/csdms-contrib/fwdet/assets/79277563/1c05e53a-a91a-489e-acb9-85092f1e0837)

Thank a lot for your help

**Comment by jeremyEudaric** [comment]
![Screenshot from 2024-05-17 12-27-08](https://github.com/csdms-contrib/fwdet/assets/79277563/aa0fcfb7-dcb6-49e9-8817-3fd93a8bba41)
l tried on a small portion but its still the same issue l guess the issue comes from my polygon. Are they a specific rules for the polygon ( which format to save it etc ) ?

**Comment by cefect** [comment]
Please provide the log file also to help me debug

**Comment by jeremyEudaric** [comment]
Thank you for our reply and time

**Comment by cefect** [comment]
your DEM is not really a DEM. fwdet expects a single band raster with elevation values (typically in meters). As yours only ranges from 0-1, so too do your water depths only range from 0-1. I'll update the documentation to make this more clear. 

I'm not sure where you obtained the DEM from, but perhaps there is some scaling value you could apply to convert it to meters. Alternatively, I've had luck using MERIT DEM or some other global DEM (e.g., FABDEM). However, I suspect there is something more accurate/detailed available for Greece.

![image](https://github.com/csdms-contrib/fwdet/assets/47092034/46e7c45e-de71-40b7-9400-51dfb0482357)

**Comment by jeremyEudaric** [comment]
Thank you for  your reply l downloaded the DEM from Copernicus. l Tried with a new DEM from https://www.usgs.gov/ with a single band (l added the file to the link its called new DEM) but l still have the issue with the poor match as explained above

**Comment by cefect** [comment]
Send me the new inputs and output. I can take a look. Maybe try forcing the minimum and maximum on the layer styles of your results layer, sometimes if there are very few real values QGiS will fail to automatically apply a style.

**Comment by jeremyEudaric** [comment]
https://drive.google.com/drive/folders/18km7boOaIIRpoDeJ7S1IlfVWItbRtolq?usp=drive_link
The new polygon and DEM, thanks a lot (DEM single band)

**Comment by cefect** [comment]
DEM_new.tif has had zeros burned from the inundation polygon. I'm not sure why you've done this, but you certainly don't want to be burning out these regions. Run with the un-burned DEM and you should get something reasonable. 

![image](https://github.com/csdms-contrib/fwdet/assets/47092034/b23e4433-f11e-4d02-b42d-a5037260c50b)

**Comment by jeremyEudaric** [comment]
Thank you for your reply and kindness l finally downloaded the DEM from MERIT DEM. l just downloaded the the DEM and used your function with my polygon ( the CRS is the same) : 
Unfortunately l still have a poor match 
![zz](https://github.com/csdms-contrib/fwdet/assets/79277563/4381f2b5-f145-499e-900a-f960f8420003)
