### ISSUE TITLE
Water Depth range issue

### ISSUE THREAD

**Issue by jeremyEudaric** [csdms-contrib/fwdet#23]
Thank your for your previous help . l got a water depth with a DEM 30 l did not find a 1 m DEM available for Europe and Greece - 1 m DEM are only available for US... Thus, l used a 30 m DEM ( as explained in the paper the results between 10m and 30 m a close). l go this results with a big range
![Screenshot from 2024-05-22 17-20-22](https://github.com/csdms-contrib/fwdet/assets/79277563/672dfb61-9485-4d0a-b0b1-1949fef07d4a)

l look into the fwDET paper and l found a similar result : 
![Screenshot from 2024-05-28 09-18-07](https://github.com/csdms-contrib/fwdet/assets/79277563/2c82b2c9-7ae5-4f07-8dbd-dbf3636f9de7)

l would like to overlay my water depth with my building footprints, in order to get an reasonable range at the building level l would like to divided the range ( first picture)  by a ratio 30 to have results at 1 m spatial resolution, the results will be rough but l think its reasonable.

What do you think about that.

Thanks a lot for your support and help for the reproducibility.

**Comment by cefect** [comment]
Thank you for the question,
If I understand, you would like to resample your 30m water depth result to 1m? This could give you a 'smoother' result, but not necessarily more accurate. Instead, I suggest focusing on playing with the parameters of FwDET. 

I hope this helps,

**Comment by jeremyEudaric** [comment]
Thank you for your help and support :) but as l said playing with the parameters of FwDET is challenging because DEM 1 m are only avaliable for US so to use FwDET worldwide its challenging..

**Comment by jeremyEudaric** [comment]
Thank for your help and kindness l think that l found the issue my inundation shore boundary raster looks like that not continuous  (picture1)

![Screenshot from 2024-05-30 15-37-23](https://github.com/csdms-contrib/fwdet/assets/79277563/2616c99d-2c59-4b17-a0c2-b70b256b944b)


So fwDETv can not clearly do the water depth if l am running you data l got this (picture2) 

![Screenshot from 2024-05-30 15-46-48](https://github.com/csdms-contrib/fwdet/assets/79277563/6dcb6ba6-0a91-4f2a-a676-9a6a3b393f4a)


so l am wondering if you have done a particular preprocessing on your flood polygon in order to have the borders like that ?

Thank you for your help and support and sorry to disturb you.

Best,

Jeremy

**Comment by jeremyEudaric** [comment]
Thanks for your help after investigation the issue is a alignment issue or a resolution issue between the flood map and DEM as you told me. 

![PIC3](https://github.com/csdms-contrib/fwdet/assets/79277563/5568e3e3-843d-4268-86b4-3dfec31123ee)

 l guess you had the same issue because you did your flood map base on satellite images. Even with the same projection, maps from two different sources (remote sensing and DEM) are never perfectly aligned. So how have you done this part on QGIS ? Because on the README they are no explanation how we could  match the polygon and the DEM that could be useful for the reproducibility, l can do it once my bug is done.

thanks a lot
